### ISSUE TITLE
Beat Hadley at making a non-shitty postgres-R adapter

### ISSUE THREAD

**Issue by robertzk** [robertzk/berdie#3]
https://github.com/rstats-db

**Comment by robertzk** [comment]
Too late.

**Comment by robertzk** [comment]
Too late.

**Comment by kirillseva** [comment]
![can't beat hadley](https://lh4.googleusercontent.com/-IU4RFAP229U/VOIu-g0jbhI/AAAAAAAAAT4/cD5nNhwcDEo/w426-h576/15%2B-%2B1)
